Feature: m-GameStats
moritzro/nba-stats pull request #19
Opened 2024-02-24 18:10 UTC by moritzro

### This PR adds:
* fixed GameCards not all taking up same width caused by lower scores
* created GameStats Module & imported it to match detail page
* changed match detail stage to accept id from url
* add util function to get game statistics
* linked logo in nav to homepage

2024-02-26 19:21 UTC, devjasha requested changes
Nice work, habe aber noch 1-2 Sachen gefunden

2024-02-26 19:21 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +  console.log(data.response);
Hier hast du vergessen, dass `console.log` weg zu machen

2024-02-26 19:21 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +            </tr>
Super Arbeit, aber findest du es nicht auch blöd, dass due hier code hast der sich perfekt aehnelt? Ich wuerde lieber eine component draus machen die du hier einfach so oft ausgibst wieviele responses du hast. verstehst du?

2024-02-26 20:15 UTC, moritzro commented on app/components/modules/GameStats/GameStats.tsx
> +  console.log(data.response);
Mein Fehler, kommt nicht wieder vor

2024-02-27 12:25 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +  console.log(data.response);
Will ich fuer dich hoffen

2024-03-01 12:18 UTC, moritzro commented
### Changes after Review:
* No longer using Tables for styling reasons
* Using a component now to display stats in GameStats module

2024-03-01 12:51 UTC, devjasha commented on app/components/custom/TeamStatsTable/TeamStatsTable.tsx
> +      <span>{points}</span>
Warum `spans`? die stehen sowieso untereinander. Kannst hier einfach `div` benutzen

2024-03-01 12:51 UTC, devjasha commented on app/components/modules/GameStats/GameStats.module.scss
> +  gap: 50px;
Hier lieber einen Wert wie 48 benutzen

2024-03-01 12:52 UTC, devjasha commented on app/components/modules/GameStats/GameStats.module.scss
> +  margin: 100px auto;
Gleiche wie darueber

2024-03-01 12:53 UTC, devjasha commented on app/components/modules/GameStats/GameStats.module.scss
> +  flex-direction: column;
wenn du aus den Stats `div` machst dann brauchst du hier auch kein `flex-direction`

2024-03-01 12:55 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +    <div className={styles.gameStatsWrapper}>
Hier wuerde ich dem Element nichts mit `wrapper` geben. Es reicht wenn es einfach `className={styles.gameStats}` ist.

2024-03-01 12:55 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +        <span>Points</span>
Hier auch das gleiche wie bei der Component. Einfach `div` benutzen

2024-03-01 12:56 UTC, devjasha commented on app/components/modules/GameStats/GameStats.tsx
> +            <img key={index} className={styles.teamLogo} src={team.team.logo} />
Hier fehlt das `alt` Attribut

2024-03-01 12:58 UTC, devjasha commented on app/components/modules/Navigation/Navigation.tsx
> +      </div>
Hier kannst du das `div` wegmachen. Wird spaeter sowieso ein Image

2024-03-01 12:59 UTC, devjasha commented on app/components/modules/Navigation/Navigation.tsx
> +                  {link.label}{" "}
warum machst du hier einen Leeren String hin? Wenn das nur dafuer da ist, dass Abstand zu sehen ist, dann lieber mit CSS loesen

2024-03-01 14:16 UTC, moritzro commented on app/components/custom/TeamStatsTable/TeamStatsTable.tsx
> +      <span>{points}</span>
Weil die davor in einem div waren, den hab ich dann rausgenommen weil der unnötig war hab dann vergessen die anzupassen

2024-03-01 14:24 UTC, moritzro commented on app/components/modules/GameStats/GameStats.module.scss
> +  gap: 50px;
Jo hab ich vergessen

2024-03-01 15:02 UTC, moritzro commented on app/components/modules/Navigation/Navigation.tsx
> +                  {link.label}{" "}
War ausversehen

2024-03-01 15:04 UTC, moritzro commented on app/components/modules/GameStats/GameStats.module.scss
> +  flex-direction: column;
Ich habs gerade getestet und das funktioniert ohne flex-direction nicht, wüsste jetzt auch nicht warum da divs oder spans nen Unterschied machen würden

2024-03-01 18:16 UTC, devjasha approved these changes
LGTM

2024-03-01 18:16 UTC, merged